def get_nifty50_stocks():
    """Returns a dictionary of NIFTY 50 stocks"""
    return {
        "Adani Enterprises (IN)": "ADANIENT.NS",
        "Adani Ports (IN)": "ADANIPORTS.NS",
        "Apollo Hospitals (IN)": "APOLLOHOSP.NS",
        "Asian Paints (IN)": "ASIANPAINT.NS",
        "Axis Bank (IN)": "AXISBANK.NS",
        "Bajaj Auto (IN)": "BAJAJ-AUTO.NS",
        "Bajaj Finance (IN)": "BAJFINANCE.NS",
        "Bajaj Finserv (IN)": "BAJAJFINSV.NS",
        "BPCL (IN)": "BPCL.NS",
        "Bharti Airtel (IN)": "BHARTIARTL.NS",
        "Britannia (IN)": "BRITANNIA.NS",
        "CIPLA (IN)": "CIPLA.NS",
        "Coal India (IN)": "COALINDIA.NS",
        "Divis Labs (IN)": "DIVISLAB.NS",
        "Dr Reddy's Labs (IN)": "DRREDDY.NS",
        "Eicher Motors (IN)": "EICHERMOT.NS",
        "Grasim (IN)": "GRASIM.NS",
        "HCL Tech (IN)": "HCLTECH.NS",
        "HDFC Bank (IN)": "HDFCBANK.NS",
        "Hero MotoCorp (IN)": "HEROMOTOCO.NS",
        "Hindalco (IN)": "HINDALCO.NS",
        "HUL (IN)": "HINDUNILVR.NS",
        "ICICI Bank (IN)": "ICICIBANK.NS",
        "IndusInd Bank (IN)": "INDUSINDBK.NS",
        "Infosys (IN)": "INFY.NS",
        "ITC (IN)": "ITC.NS",
        "JSW Steel (IN)": "JSWSTEEL.NS",
        "Kotak Mahindra (IN)": "KOTAKBANK.NS",
        "LTIMindtree (IN)": "LTIM.NS",
        "Larsen & Toubro (IN)": "LT.NS",
        "M&M (IN)": "M&M.NS",
        "Maruti Suzuki (IN)": "MARUTI.NS",
        "NTPC (IN)": "NTPC.NS",
        "Nestle India (IN)": "NESTLEIND.NS",
        "ONGC (IN)": "ONGC.NS",
        "Power Grid Corp (IN)": "POWERGRID.NS",
        "Reliance Industries (IN)": "RELIANCE.NS",
        "SBI Life Insurance (IN)": "SBILIFE.NS",
        "SBI (IN)": "SBIN.NS",
        "Sun Pharma (IN)": "SUNPHARMA.NS",
        "TCS (IN)": "TCS.NS",
        "Tata Consumer (IN)": "TATACONSUM.NS",
        "Tata Motors (IN)": "TATAMOTORS.NS",
        "Tata Steel (IN)": "TATASTEEL.NS",
        "Tech Mahindra (IN)": "TECHM.NS",
        "Titan Company (IN)": "TITAN.NS",
        "UPL (IN)": "UPL.NS",
        "UltraTech Cement (IN)": "ULTRACEMCO.NS",
        "Wipro (IN)": "WIPRO.NS"
    }

def get_sensex_stocks():
    """Returns a dictionary of SENSEX stocks"""
    return {
        "Axis Bank (SENSEX)": "AXISBANK.BO",
        "Bajaj Finance (SENSEX)": "BAJFINANCE.BO",
        "Bajaj Finserv (SENSEX)": "BAJAJFINSV.BO",
        "HCL Technologies (SENSEX)": "HCLTECH.BO",
        "HDFC Bank (SENSEX)": "HDFCBANK.BO",
        "ICICI Bank (SENSEX)": "ICICIBANK.BO",
        "IndusInd Bank (SENSEX)": "INDUSINDBK.BO",
        "Infosys (SENSEX)": "INFY.BO",
        "ITC (SENSEX)": "ITC.BO",
        "Kotak Mahindra (SENSEX)": "KOTAKBANK.BO",
        "Larsen & Toubro (SENSEX)": "LT.BO",
        "M&M (SENSEX)": "M&M.BO",
        "Maruti Suzuki (SENSEX)": "MARUTI.BO",
        "NTPC (SENSEX)": "NTPC.BO",
        "Nestle India (SENSEX)": "NESTLEIND.BO",
        "Reliance Industries (SENSEX)": "RELIANCE.BO",
        "SBI (SENSEX)": "SBIN.BO",
        "TCS (SENSEX)": "TCS.BO",
        "Tata Motors (SENSEX)": "TATAMOTORS.BO",
        "Tata Steel (SENSEX)": "TATASTEEL.BO",
        "Tech Mahindra (SENSEX)": "TECHM.BO",
        "Titan Company (SENSEX)": "TITAN.BO",
        "UltraTech Cement (SENSEX)": "ULTRACEMCO.BO",
        "Wipro (SENSEX)": "WIPRO.BO"
    }

def get_default_stocks():
    """Returns a dictionary of default stocks"""
    return {
        "Tesla (US)": "TSLA",
        "Apple (US)": "AAPL",
        "Reliance Industries (IN)": "RELIANCE.NS",
        "HDFC Bank (IN)": "HDFCBANK.NS",
        "TCS (IN)": "TCS.NS"
    } 